spring:
  application:
    name: register-service
  kafka:
    bootstrap-servers:
      - localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      retries: 3
      client-id: register-producer-local
      transaction-id-prefix: reg
      properties:
        enable:
          idempotence: true
        transactional:
          id: reg

kafka:
  fraud: fraud-topic